#!/usr/bin/env node
'use strict';

/**
 * `npm run setup` — interactive first-run wizard for Mail Workflow.
 *
 * Goal: a newcomer runs one command and ends up with a valid `.env`, without
 * having read any documentation first.
 *
 * Design notes:
 *  - Node built-ins only (it must run before `npm install` if needed).
 *  - The generated `.env` is rendered FROM `.env.example`, so its comments,
 *    section headers and variable order survive.
 *  - Nothing is written until the very last step, and the write is atomic
 *    (temp file + rename), so Ctrl+C can never leave a half-written `.env`.
 *  - Secret values are never echoed back or printed in summaries.
 */

const crypto = require('node:crypto');
const fs = require('node:fs');
const path = require('node:path');
const readline = require('node:readline/promises');

const {
  ENV_PATH,
  ENV_BACKUP_PATH,
  ENV_EXAMPLE_PATH,
  PROJECT_ROOT,
  MIN_NODE_MAJOR,
  DEFAULT_PORT,
  MANAGED_KEYS,
  color,
  ignoreEpipe,
  nodeMajor,
  isNodeSupported,
  readEnvFile,
  isBlank,
  renderEnvFromTemplate,
  localUris,
} = require('./lib/env');

/** Exit code used when the user aborts with Ctrl+C (128 + SIGINT). */
const EXIT_CANCELLED = 130;

/** Fallback template, used only if `.env.example` is missing or unreadable. */
const FALLBACK_TEMPLATE = [
  '# Mail Workflow — environment',
  '# Generated by `npm run setup`. NEVER commit this file.',
  '',
  'SESSION_SECRET=',
  'APP_ORIGIN=',
  'REDIS_URL=',
  'PORT=3000',
  '# NODE_ENV=production',
  '',
  '# --- Gmail OAuth (Google Cloud Console) ---',
  'GMAIL_CLIENT_ID=',
  'GMAIL_CLIENT_SECRET=',
  'GMAIL_REDIRECT_URI=',
  '',
  '# --- Outlook OAuth (Azure AD) ---',
  'OUTLOOK_CLIENT_ID=',
  'OUTLOOK_CLIENT_SECRET=',
  'OUTLOOK_TENANT_ID=common',
  'OUTLOOK_REDIRECT_URI=',
  '',
  '# --- AI proxy (/api/ai/*) ---',
  'ALLOW_LOCAL_AI=',
  'OLLAMA_API_KEY=',
  '',
].join('\n');

// --- Small output helpers ----------------------------------------------------

ignoreEpipe();

const say = (line = '') => process.stdout.write(`${line}\n`);
const rule = () => say(color.dim('-'.repeat(72)));

/**
 * Print a numbered section title.
 * @param {number} step
 * @param {string} title
 */
function section(step, title) {
  say();
  say(color.bold(`[${step}] ${title}`));
  rule();
}

// --- Prompt helpers ----------------------------------------------------------

/**
 * Ask a free-text question.
 * @param {readline.Interface} rl
 * @param {string} question
 * @param {{defaultValue?: string, required?: boolean, validate?: (v: string) => string|null}} [opts]
 * @returns {Promise<string>}
 */
async function ask(rl, question, opts = {}) {
  const { defaultValue = '', required = false, validate } = opts;
  for (;;) {
    const suffix = defaultValue ? ` ${color.dim(`[${defaultValue}]`)}` : '';
    // Values are trimmed: pasted credentials very often carry trailing spaces
    // or a stray newline, which is a real and confusing failure mode.
    const answer = (await rl.question(`${question}${suffix} > `)).trim();
    const value = answer === '' ? defaultValue : answer;
    if (required && value === '') {
      say(color.red('    This value is required.'));
      continue;
    }
    if (validate) {
      const problem = validate(value);
      if (problem) {
        say(color.red(`    ${problem}`));
        continue;
      }
    }
    return value;
  }
}

/**
 * Ask a yes/no question.
 * @param {readline.Interface} rl
 * @param {string} question
 * @param {boolean} [defaultYes]
 * @returns {Promise<boolean>}
 */
async function askYesNo(rl, question, defaultYes = false) {
  const hint = defaultYes ? 'Y/n' : 'y/N';
  for (;;) {
    const answer = (await rl.question(`${question} ${color.dim(`(${hint})`)} > `))
      .trim()
      .toLowerCase();
    if (answer === '') return defaultYes;
    if (['y', 'yes'].includes(answer)) return true;
    if (['n', 'no'].includes(answer)) return false;
    say(color.red('    Please answer "y" or "n".'));
  }
}

/**
 * Ask the user to pick one entry from a numbered list.
 * @param {readline.Interface} rl
 * @param {string} question
 * @param {string[]} options
 * @param {number} [defaultIndex] Zero-based.
 * @returns {Promise<number>} Zero-based index of the chosen option.
 */
async function askChoice(rl, question, options, defaultIndex = 0) {
  say(question);
  options.forEach((label, index) => say(`    ${index + 1}) ${label}`));
  for (;;) {
    const answer = (await rl.question(`  Choice ${color.dim(`[${defaultIndex + 1}]`)} > `)).trim();
    if (answer === '') return defaultIndex;
    const picked = Number.parseInt(answer, 10);
    if (Number.isInteger(picked) && picked >= 1 && picked <= options.length) {
      return picked - 1;
    }
    say(color.red(`    Enter a number between 1 and ${options.length}.`));
  }
}

// --- Validators --------------------------------------------------------------

/**
 * Validate a TCP port entered by the user.
 * @param {string} value
 * @returns {string|null} An error message, or null when valid.
 */
function validatePort(value) {
  const port = Number.parseInt(value, 10);
  if (!Number.isInteger(port) || String(port) !== value.trim()) {
    return 'Enter a number, e.g. 3000.';
  }
  if (port < 1 || port > 65535) return 'A port must be between 1 and 65535.';
  if (port < 1024) {
    return 'Ports below 1024 need administrator privileges. Pick 3000 or higher.';
  }
  return null;
}

/**
 * Validate a redis:// URL entered by the user.
 * @param {string} value
 * @returns {string|null}
 */
function validateRedisUrl(value) {
  try {
    const url = new URL(value);
    if (!['redis:', 'rediss:'].includes(url.protocol)) {
      return 'The URL must start with redis:// or rediss://';
    }
    if (!url.hostname) return 'The URL has no host.';
    return null;
  } catch {
    return 'Not a valid URL. Example: redis://localhost:6379';
  }
}

// --- Provider instructions ---------------------------------------------------

/**
 * Print the condensed Google Cloud console steps.
 * @param {string} redirectUri Exact URI the user must register.
 */
function printGoogleSteps(redirectUri) {
  say();
  say(color.cyan('  Google Cloud Console — create your OAuth client'));
  say('    1. Open https://console.cloud.google.com/ and create (or select) a project.');
  say('    2. "APIs & Services" > "Library" > enable the "Gmail API".');
  say('    3. "APIs & Services" > "OAuth consent screen": User type "External",');
  say('       publishing status "Testing", then add YOUR OWN Google address');
  say('       under "Test users" (no Google verification needed for personal use).');
  say('    4. "APIs & Services" > "Credentials" > "Create credentials" >');
  say('       "OAuth client ID" > Application type "Web application".');
  say('    5. Under "Authorized redirect URIs", add EXACTLY:');
  say(`         ${color.bold(redirectUri)}`);
  say('    6. Create, then copy the Client ID and the Client secret below.');
  say(color.dim('    Full guide: docs/setup/google-cloud.md'));
  say();
}

/**
 * Print the condensed Azure portal steps.
 * @param {string} redirectUri Exact URI the user must register.
 */
function printAzureSteps(redirectUri) {
  say();
  say(color.cyan('  Azure Portal — register your application'));
  say('    1. Open https://portal.azure.com/ > "Microsoft Entra ID" >');
  say('       "App registrations" > "New registration".');
  say('    2. Supported account types: "Accounts in any organizational directory');
  say('       and personal Microsoft accounts" (needed for outlook.com addresses).');
  say('    3. Redirect URI: platform "Web", value EXACTLY:');
  say(`         ${color.bold(redirectUri)}`);
  say('    4. Register, then copy "Application (client) ID" from the Overview page.');
  say('    5. "Certificates & secrets" > "New client secret" > copy the');
  say('       secret VALUE (not the Secret ID — the value is shown only once).');
  say('    6. "API permissions" > "Add a permission" > "Microsoft Graph" >');
  say('       "Delegated": Mail.Read, Mail.Send, User.Read, offline_access.');
  say(color.dim('    Full guide: docs/setup/azure-ad.md'));
  say();
}

// --- .env writing ------------------------------------------------------------

/**
 * Render the final `.env` content from the `.env.example` template.
 * @param {Record<string, string>} values
 * @returns {string}
 */
function buildEnvContent(values) {
  let template = FALLBACK_TEMPLATE;
  try {
    template = fs.readFileSync(ENV_EXAMPLE_PATH, 'utf8');
  } catch {
    say(color.yellow('  Note: .env.example could not be read — using the built-in template.'));
  }
  return renderEnvFromTemplate(template, values);
}

/**
 * Write `.env` atomically: a temp file in the project root, then a rename.
 * Guarantees no half-written `.env` if the process dies mid-write.
 * @param {string} content
 */
function writeEnvAtomically(content) {
  const tmpPath = path.join(PROJECT_ROOT, `.env.tmp-${crypto.randomBytes(6).toString('hex')}`);
  try {
    // 0o600 is a no-op on Windows but protects the file on macOS/Linux.
    fs.writeFileSync(tmpPath, content, { encoding: 'utf8', mode: 0o600 });
    fs.renameSync(tmpPath, ENV_PATH);
  } catch (err) {
    try {
      fs.unlinkSync(tmpPath);
    } catch {
      /* nothing to clean */
    }
    throw err;
  }
}

/**
 * Show which managed variables an existing `.env` defines. Values are NEVER
 * printed — only "set" / "not set".
 * @param {Record<string, string>} values
 */
function printExistingSummary(values) {
  const width = Math.max(...MANAGED_KEYS.map((key) => key.length));
  for (const key of MANAGED_KEYS) {
    const isSet = !isBlank(values[key]);
    const label = isSet ? color.green('set') : color.dim('not set');
    say(`    ${key.padEnd(width)}  ${label}`);
  }
  say(color.dim('    (values are never displayed)'));
}

// --- Wizard ------------------------------------------------------------------

/**
 * Run the whole interactive wizard.
 * @param {readline.Interface} rl
 * @param {{force: boolean}} flags
 * @returns {Promise<number>} Process exit code.
 */
async function runWizard(rl, flags) {
  // -- Step 1: banner + Node version ----------------------------------------
  say();
  say(color.bold('  Mail Workflow — setup'));
  say(color.dim('  Creates your .env file. Nothing is written until the last step.'));
  say();

  if (!isNodeSupported()) {
    say(color.red(`  Node.js ${MIN_NODE_MAJOR} or newer is required.`));
    say(`  Detected: ${process.version} (major ${nodeMajor()})`);
    say('  Fix: install Node.js LTS from https://nodejs.org/ (or use nvm:');
    say(`       "nvm install ${MIN_NODE_MAJOR}" then "nvm use ${MIN_NODE_MAJOR}"),`);
    say('       then run "npm run setup" again.');
    return 1;
  }
  say(`  Node.js ${process.version} ${color.green('ok')}`);

  // -- Step 2: browser requirement (cannot be detected) ----------------------
  say();
  say(color.yellow('  Browser requirement:'));
  say('  Mail Workflow uses the File System Access API to store your emails in a');
  say('  local folder you choose. It works in Chrome or Edge 86+ ONLY.');
  say('  Firefox, Safari and mobile browsers are not supported.');

  // -- Step 3: existing .env -------------------------------------------------
  let step = 0;
  const nextStep = (title) => section((step += 1), title);

  const existing = readEnvFile(ENV_PATH);
  if (existing.exists) {
    nextStep('An existing .env was found');
    printExistingSummary(existing.values);
    say();

    if (!flags.force) {
      const keep = await askYesNo(rl, '  Keep it and exit now?', true);
      if (keep) {
        say();
        say(color.green('  Nothing changed. Your .env was left untouched.'));
        say('  Check it with "npm run doctor", or redo it with');
        say('  "npm run setup -- --force".');
        return 0;
      }
    }

    try {
      fs.copyFileSync(ENV_PATH, ENV_BACKUP_PATH);
      say(color.yellow(`  Your previous .env was copied to ${path.basename(ENV_BACKUP_PATH)}`));
    } catch (err) {
      say(color.red(`  Could not back up .env (${err.code || err.message}).`));
      say('  Fix: close any program holding the file, or copy it yourself first.');
      const proceed = await askYesNo(rl, '  Continue and overwrite anyway?', false);
      if (!proceed) return 1;
    }
  }

  // -- Step 4: providers -----------------------------------------------------
  nextStep('Email providers');
  const providerChoice = await askChoice(
    rl,
    '  Which mailbox(es) do you want to connect?',
    ['Gmail only', 'Outlook only', 'Both Gmail and Outlook'],
    0
  );
  const useGmail = providerChoice === 0 || providerChoice === 2;
  const useOutlook = providerChoice === 1 || providerChoice === 2;

  // Redirect URIs are shown for the default port first; the "Server port" step
  // re-displays them if the user picks another port (they must match the value
  // registered in the provider console, character for character).
  const defaultUris = localUris(DEFAULT_PORT);

  /** @type {Record<string, string>} */
  const values = {};
  for (const key of MANAGED_KEYS) values[key] = '';

  // -- Step 5: credentials ---------------------------------------------------
  if (useGmail) {
    nextStep('Gmail credentials');
    printGoogleSteps(defaultUris.gmail);
    say(color.dim('  (What you type stays visible in the terminal.)'));
    values.GMAIL_CLIENT_ID = await ask(rl, '  Gmail client ID', {
      required: true,
    });
    if (!values.GMAIL_CLIENT_ID.endsWith('.apps.googleusercontent.com')) {
      say(
        color.yellow(
          '    Warning: a Google client ID normally ends with ".apps.googleusercontent.com".'
        )
      );
      say(color.yellow('    Double-check you copied the Client ID and not the project number.'));
    }
    values.GMAIL_CLIENT_SECRET = await ask(rl, '  Gmail client secret', {
      required: true,
    });
  }

  if (useOutlook) {
    nextStep('Outlook credentials');
    printAzureSteps(defaultUris.outlook);
    say(color.dim('  (What you type stays visible in the terminal.)'));
    values.OUTLOOK_CLIENT_ID = await ask(rl, '  Outlook application (client) ID', {
      required: true,
    });
    values.OUTLOOK_CLIENT_SECRET = await ask(rl, '  Outlook client secret VALUE', {
      required: true,
    });
    values.OUTLOOK_TENANT_ID = await ask(
      rl,
      '  Outlook tenant ID ("common" works for personal + work accounts)',
      { defaultValue: 'common', required: true }
    );
  }

  // -- Step 6: session secret ------------------------------------------------
  values.SESSION_SECRET = crypto.randomBytes(32).toString('hex');
  say();
  say(color.green('  A random SESSION_SECRET (32 bytes) was generated for you.'));

  // -- Step 7: port + redirect URIs -----------------------------------------
  nextStep('Server port');
  say(`  The app listens on this port. Default: ${DEFAULT_PORT}.`);
  const port = await ask(rl, '  Port', {
    defaultValue: String(DEFAULT_PORT),
    required: true,
    validate: validatePort,
  });
  const uris = localUris(port);
  values.PORT = String(port);
  values.APP_ORIGIN = uris.origin;
  values.GMAIL_REDIRECT_URI = useGmail ? uris.gmail : '';
  values.OUTLOOK_REDIRECT_URI = useOutlook ? uris.outlook : '';

  if (String(port) !== String(DEFAULT_PORT)) {
    say();
    say(color.yellow('  Port changed — your redirect URIs changed too.'));
    say('  The URI registered in the provider console MUST match exactly.');
    say('  Go back and register these instead:');
    if (useGmail)
      say(`    Google Cloud > Credentials > your OAuth client:  ${color.bold(uris.gmail)}`);
    if (useOutlook)
      say(`    Azure > App registration > Authentication:      ${color.bold(uris.outlook)}`);
    say();
    await rl.question('  Press Enter once that is done > ');
  }

  // -- Step 8: AI assistant --------------------------------------------------
  nextStep('AI assistant (optional)');
  const aiChoice = await askChoice(
    rl,
    '  Which AI provider will you use?',
    [
      'Skip for now (you can enable it later in the app)',
      'Ollama, running locally on your machine',
      'OpenAI (cloud)',
      'Anthropic (cloud)',
      'Another OpenAI-compatible endpoint',
    ],
    0
  );

  if (aiChoice === 1) {
    values.ALLOW_LOCAL_AI = 'true';
    say();
    say(color.green('  ALLOW_LOCAL_AI=true will be written.'));
    say('  This lets the anti-SSRF guard reach 127.0.0.1:11434 (Ollama).');
    say('  Still to do outside this wizard:');
    say('    - install Ollama from https://ollama.com/');
    say('    - pull a model, e.g. "ollama pull llama3.1"');
    say('    - keep "ollama serve" running while you use the app');
  } else if (aiChoice >= 2) {
    say();
    say('  Nothing to configure here.');
    say('  Your API key is entered in the browser UI (AI settings panel), stored in');
    say('  your browser only, and forwarded to the provider through the /api/ai proxy.');
    say('  It is never written to .env, never logged and never persisted server-side.');
  } else {
    say();
    say(color.dim('  Skipped. The AI features stay available but unconfigured.'));
  }

  // -- Step 9: Redis ---------------------------------------------------------
  nextStep('Redis (optional)');
  say('  Without Redis, sessions live in memory: restarting the server logs you out.');
  const wantRedis = await askYesNo(rl, '  Configure a Redis URL?', false);
  if (wantRedis) {
    values.REDIS_URL = await ask(rl, '  Redis URL', {
      defaultValue: 'redis://localhost:6379',
      required: true,
      validate: validateRedisUrl,
    });
  }

  // -- Step 10: write --------------------------------------------------------
  nextStep('Writing .env');
  const content = buildEnvContent(values);
  writeEnvAtomically(content);
  say(color.green(`  Wrote ${ENV_PATH}`));
  say(color.dim('  (.env is git-ignored — never commit it.)'));

  // -- Step 11: next steps ---------------------------------------------------
  say();
  rule();
  say(color.bold('  Setup complete. Next steps:'));
  say();
  say('    1. npm ci          (if you have not installed dependencies yet)');
  say('    2. npm start');
  say(`    3. open ${color.bold(uris.origin)} in Chrome or Edge`);
  say();
  say('  In the app: connect your mailbox, pick a local folder, download, then');
  say('  select a subject to see its conversation tree.');
  say();
  say(color.dim('  Something not working? Run: npm run doctor'));
  say();
  return 0;
}

// --- Entry point -------------------------------------------------------------

/**
 * Parse the CLI flags this script understands.
 * @param {string[]} argv
 * @returns {{force: boolean, help: boolean}}
 */
function parseFlags(argv) {
  return {
    force: argv.includes('--force') || argv.includes('-f'),
    help: argv.includes('--help') || argv.includes('-h'),
  };
}

/** Print usage. */
function printHelp() {
  say('Usage: npm run setup [-- --force]');
  say();
  say('  Interactive wizard that creates the .env file for Mail Workflow.');
  say();
  say('  --force, -f   Overwrite an existing .env without asking');
  say('                (the previous file is still copied to .env.bak).');
  say('  --help,  -h   Show this message.');
}

async function main() {
  const flags = parseFlags(process.argv.slice(2));
  if (flags.help) {
    printHelp();
    return 0;
  }

  // A wizard cannot run without a keyboard. Fail fast instead of hanging on a
  // question nobody can answer (CI, `npm run setup < /dev/null`, Docker build).
  if (!process.stdin.isTTY) {
    say(color.red('  npm run setup needs an interactive terminal.'));
    say('  Standard input is not a TTY, so the questions cannot be answered.');
    say();
    say('  Fix: run it directly in a terminal (PowerShell, cmd, bash), without');
    say('       piping or redirecting input. For an unattended install, copy');
    say('       .env.example to .env and fill the values yourself, then run');
    say('       "npm run doctor" to verify them.');
    return 1;
  }

  const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout,
  });

  // Ctrl+C: exit quietly. Nothing has been written yet at any point before the
  // final atomic rename, so there is nothing to clean up.
  rl.on('SIGINT', () => {
    say();
    say(color.yellow('  Setup cancelled. No file was created or modified.'));
    rl.close();
    process.exit(EXIT_CANCELLED);
  });

  try {
    return await runWizard(rl, flags);
  } finally {
    rl.close();
  }
}

main()
  .then((code) => {
    process.exitCode = code;
  })
  .catch((err) => {
    // AbortError / ERR_USE_AFTER_CLOSE happen when stdin closes mid-question.
    if (err && (err.name === 'AbortError' || err.code === 'ERR_USE_AFTER_CLOSE')) {
      say();
      say(color.yellow('  Setup cancelled. No file was created or modified.'));
      process.exitCode = EXIT_CANCELLED;
      return;
    }
    say();
    say(color.red(`  Setup failed: ${err && err.message ? err.message : err}`));
    say('  Fix: check that you can write files in this folder, then try again.');
    say('  You can also copy .env.example to .env and edit it by hand.');
    process.exitCode = 1;
  });
